spring:
  datasource:
    url: jdbc:mysql://localhost:3306/info_identity_server
    username: info
    password: Secret@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true    
    database-platform: org.hibernate.dialect.MySQL5Dialect
    
server:
  servlet:
    context-path: /uaa
  port: 8081
                    
     

  
        
